name: "nodejs-app-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    # - /app/logs/*.log  
    - /app/logs/app.log  
  fields:
    service: nodejs-app
  fields_under_root: true
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'

- type: log
  scan_frequency: 1s
  enabled: true
  paths:
      # - /app/logs/*.log 
    - /app/logs/appv2.log  
  fields:
    service: nodejs-appv2
  fields_under_root: true
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'


# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "nodejs-app"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "nodejs-app-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.equals:
        service: "nodejs-app"
    - index: "nodejs-appv2-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.equals:
        service: "nodejs-appv2"
